spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf-8
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lmy.shopping.entity

logging:
  level:
    com.lmy.shopping.mapper: debug